# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: Prismarine
patreon: alphakr93_
issuehunt: alphakr93
ko_fi: alphakr93
liberapay: alphakr93
custom: ["https://toon.at/donate/637349490049950363", "https://www.paypal.me/alphakr93", "https://www.buymeacoffee.com/alpha93"]
